import React from 'react'
import '../../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from '../components/header'
import Head from 'next/head'
import storage from 'utils/storage'
import { THEME } from 'constants/storage-keys'

function MyApp({ Component, pageProps }: AppProps) {
	React.useEffect(() => {
		const theme = storage.get(THEME)
		if (!theme) {
			storage.set(THEME, 'light')
		}
	}, [])

	return (
		<>
			<Head>
				<title> Site of Trevor Bagwell </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Component {...pageProps} />
		</>
	)
}

export default MyApp
